숫자 야구 게임 미션 1차 제출
LIN-KHU/java-baseball pull request #5
Opened 2024-01-18 12:22 UTC by MarriedSenior

저번에 예외처리나 이것저것 배우고 나니 이번 미션때는 코딩하면서도 이 부분은 예외처리가 필요하겠구나를 코딩하면서 생각하게 됩니다. 

함수화 하기, 예외처리, 인풋뷰 아웃풋뷰 구현하겠습니다. 일단 기본 기능만 구현해서 올립니다!

2024-01-18 14:34 UTC, woosung1223 requested changes
안녕하세요 대욱님!

확실히 저번 미션에 비해 더 성장하신 것 같습니다 🙂

로직 자체는 잘 짜주셨는데, 남은 기간동안 말씀해주신 것처럼 메소드 분리 + 객체 분리를 하시면 더욱 좋은 코드가 될 것 같습니다!

추가적으로, 세세한 요구사항을 만족하지 않는 부분이 꽤 있는 것 같습니다. 기능을 완성하는 것도 백엔드 개발자에게 중요한 역량이긴 하나, 요구사항을 만족시키는 것도 상당히 중요한 부분이어서요!

기능 목록 작성이나, 기타 요구사항(커밋 컨벤션 등) 등을 확인해주시면 감사하겠습니다!

수정하시고 다시 요청주세요~! 고생하셨습니다!

2024-01-18 14:34 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +        Scanner scanner = new Scanner(System.in);
![image](https://github.com/LIN-KHU/java-baseball/assets/78679830/28a84cb3-61fa-4721-8568-d7e7cda2bf96)

Scanner 사용도 좋지만 해당 미션에서는 요구사항으로 `Randoms`, `Console` 라이브러리를 사용하기를 권장하고 있습니다!

나중에 설명드리겠지만, 해당 라이브러리를 사용하지 않으면 테스트가 통과하지 않습니다..!

변경하시고 한 번 테스트를 돌려보시면 통과하시는 걸 확인하실 수 있을겁니다!

2024-01-18 14:34 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +        Random random = new Random();
이 부분도 앞서 말씀드린 것과 같이 `Randoms` 라이브러리를 사용해주세요~!

2024-01-18 14:34 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +        List<Integer> Numbers = new ArrayList<Integer>(3);
변수명은 camel-case에 따라서 작성해주세요~

참고로, ArrayList 객체를 생성할 때에는 일반적으로 capacity를 지정할 필요는 없습니다.

지정하지 않으면 10의 크기를 가진 배열로 내부적으로 초기화가 되는데, 큰 성능 차이는 없으므로  `new ArrayList<>();` 로도 충분할 것 같습니다!

2024-01-18 14:34 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +        return Numbers;
`numbers`는 3개의 숫자로 구성된 List죠!

이 부분을 객체로 뽑아낼 순 없을까요?

2024-01-18 14:34 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +    // 3. 각 자리의 숫자가 0이 아니고, 서로 같지 않아야 함
👍

2024-01-18 14:34 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +                System.exit(0);
2를 입력받은 경우 게임이 종료되어야 하는데, 0을 입력받았을 때 게임을 종료하고 있네요!

2024-01-20 19:41 UTC, MarriedSenior commented on src/main/java/baseball/Application.java
> +        Scanner scanner = new Scanner(System.in);
수정 완료

2024-01-20 19:42 UTC, MarriedSenior commented on src/main/java/baseball/Application.java
> +        Random random = new Random();
수정 완료.

2024-01-20 19:43 UTC, MarriedSenior commented on src/main/java/baseball/Application.java
> +        List<Integer> Numbers = new ArrayList<Integer>(3);
수정완료.

2024-01-20 19:43 UTC, MarriedSenior commented on src/main/java/baseball/Application.java
> +        return Numbers;
이건 무슨 뜻일까요? 이해가 안돼서 조금 더 설명 부탁드립니다.

2024-01-20 19:44 UTC, MarriedSenior commented on src/main/java/baseball/Application.java
> +                System.exit(0);
수정 완료.

2024-01-21 11:54 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +        return Numbers;
```java

public class BaseballNumber {

  private final List<Integer> numbers;

 ...
}
```
이런 형태의 객체 구성을 의도드린 것이었습니다!

2024-01-21 15:24 UTC, MarriedSenior commented on src/main/java/baseball/Application.java
> +        return Numbers;
수정완료.

2024-01-21 15:41 UTC, MarriedSenior commented on src/main/java/baseball/view/InputView.java
> +    }
또한 무엇을 예외처리해야할지는 알겠습니다만 저렇게 여러가지 경우를 딱 하나의 IllegalArgumentexception을 날린다는게 무슨 의미인지 이해가 아직도 안됐습니다 이 두가지 부분에 대한 피드백 부탁드립니다 멘토님

2024-01-21 15:41 UTC, MarriedSenior commented on src/main/java/baseball/Application.java
> +        OutputView output = new OutputView();
인풋뷰와 아웃풋뷰로 클래스 분리는 해보았으나 중복해서 함수마다 선언하는 것이 불편합니다. 개선방법이 있을까요?

2024-01-21 15:46 UTC, woosung1223 commented on src/main/java/baseball/view/InputView.java
> +    }
여러 케이스에 대해 `IllegalArgumentException`을 발생시키는게 요구사항이었죠!

가령 여러가지 경우를 하나의 예외로 처리할 때에는, 크게 다른 건 없고 다음과 같은 형태로 처리할 수 있습니다.

```java
public int typeGetNumber() {
    int number = Integer.parseInt(Console.readLine());
    
    if (number < 1 || number > 9) {
        throw new IllegalArgumentException("숫자 범위가 올바르지 않습니다.");
    }
    if (다른 조건) {
        throw new IllegalArgumentException("예외 메세지");
    }
}
```

2024-01-21 15:48 UTC, woosung1223 commented on src/main/java/baseball/Application.java
> +        OutputView output = new OutputView();
좋은 고민입니다 👍

여러 메소드에서 공통적으로 사용되는 객체는 보통 '필드'로 선언합니다.
한 번 찾아보시면 바로 이해하실 수 있을 것 같습니다!

2024-01-21 16:16 UTC, loveysuby commented
반갑습니다. 리뷰 요청 주셔서 덕분에 같은 문제를 두고 제 생각을 공유해보고자 해요. 
좋다고 생각되는 부분을 취사선택 하셔서 가져가주시면 감사하겠습니다 :)

2024-01-21 17:02 UTC, loveysuby commented on src/main/java/baseball/view/InputView.java
> +    public int typeGetNumber(){
Java API는 광범위한 요인에 의해 발생할 수 있는 예외들 중 기준이 될 수 있는 예외사항을 묶어서 표준 예외 로 제공하고 있습니다.
NullPointerException, IllegalArgumentExcepion 등이 표준 예외에 해당되고 있습니다.

```java
    public int typeRestartNumber(){
        return Integer.parseInt(Console.readLine());
    }
``` 
표준 예외가 없다면, 작성해주신 `typeRestartNumber` 메소드에서 아무런 입력값을 받지 못 한 경우에 어떻게 프로그램이 작동해야 할지 직접 지정해주셔야 할 거예요. 그렇게 따지면 엄청나게 많은 예외 고려사항들이 생기니 예외처리를 위한 프로그래밍을 하는 셈이 됩니다.
 
예외 케이스 주석을 보면 나이브하게 `숫자를 입력하는 상황에서의 예외` 와 `입력값의 의미에 관한 예외` 로 분리할 수 있겠습니다. 
이런 케이스들은 모두 발생하면 `IllegalArgumentException`을 발생시키도록 요구되었어요. 정확하게 파악하신 것 같습니다!

하지만 작성하신 코드를 다른 사람이 돌려보다가 에러가 발생했는데 _그게 전부 `IllegalArgumentException`라고만 나오고 원인을 디버깅해야 된다면 그것 역시 시간적 비용이 발생_할 수도 있을 거 같네요. 이 부분에 대해서 고민해보시면 좋겠습니다.

여러 예외 케이스를 하나의 `Exception`으로 통일하는 것이 명확한 장단점을 가지고 있다는 것을 생각해보시면 좋을 것 같아요!

2024-01-21 17:17 UTC, loveysuby commented on src/main/java/baseball/Application.java
> +    public static void printResultIfGameFinish() {
게임 종료시 결과를 출력하는 메소드를 `Application`에서 구현해주셨네요!

OutputVIew에서도 유사한 이름의 메소드명을 가지고 있어서, 게임이 실행되는 여기서는 print 대신 다른 메소드 명을 사용하는 것은 어떻게 생각하시는지 궁금합니다 :)

2024-01-21 17:21 UTC, loveysuby commented on src/main/java/baseball/Application.java
> +    public static void printResultIfGameNotFinish(int strike, int ball) {
`static`으로 선언된 정적 메소드로 게임의 흐름이 진행되고 있네요!
정적 메소드를 활용하신 이유가 있다면 어떤 것인지 궁금합니다 🕵️‍♂️ 

정적 메소드 내부에서 선언되는 필드는 정적 필드로 간주됩니다. 
output 변수 같은 경우 아래와 같은 셈이 됩니다.
```java
static OutputView output = new OutputView();
``` 
`Application`에서 정적 메소드로 선언된 부분의 내부 필드는 메소드 밖으로 분리해주셔도 동일한 기능을 수행하므로 가독성을 향상시켜볼 수 있을 것 같아요!

2024-01-25 04:09 UTC, merged